# Generated by Django 4.2.4 on 2023-09-04 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles_app', '0002_article_created_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-created_time',), 'verbose_name': 'مقاله', 'verbose_name_plural': 'مقالات'},
        ),
    ]
