# Generated by Django 4.2.4 on 2023-09-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles_app', '0003_alter_article_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='second_image',
            field=models.ImageField(null=True, upload_to='images/article_images'),
        ),
    ]
