# Generated by Django 4.2.4 on 2023-09-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles_app', '0004_article_second_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ تولید'),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(max_length=1500, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='images/article_images', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pdf_file',
            field=models.FileField(upload_to='pdfs/article_pdf', verbose_name='فایل'),
        ),
        migrations.AlterField(
            model_name='article',
            name='persian_description',
            field=models.TextField(max_length=1500, verbose_name='توضیحات(فارسی)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='persian_title',
            field=models.CharField(max_length=300, verbose_name='عنوان(فارسی)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='second_image',
            field=models.ImageField(null=True, upload_to='images/article_images', verbose_name='عکس دوم'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=300, verbose_name='عنوان'),
        ),
    ]
