# Generated by Django 4.2.4 on 2023-08-11 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects_app', '0004_image_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.ImageField(upload_to='images/content_images')),
                ('video', models.FileField(blank=True, upload_to='videos/content_videos')),
                ('title', models.CharField(max_length=400)),
                ('persian_title', models.CharField(max_length=400)),
                ('description', models.CharField(max_length=1500)),
                ('persian_description', models.CharField(max_length=1500)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان تولید')),
                ('images', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='projects_app.image')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
