# Generated by Django 4.2.4 on 2023-08-18 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ('-created_at',), 'verbose_name': 'محتوا', 'verbose_name_plural': 'محتوا'},
        ),
    ]
