# Generated by Django 4.2.4 on 2023-09-12 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0003_content_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='images',
        ),
        migrations.AddField(
            model_name='content',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/content_images', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='content',
            name='cover_image',
            field=models.ImageField(upload_to='images/content_images', verbose_name='عکس کاور'),
        ),
        migrations.AlterField(
            model_name='content',
            name='description',
            field=models.CharField(max_length=1500, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='content',
            name='persian_description',
            field=models.CharField(max_length=1500, verbose_name='توضیحات(فارسی)'),
        ),
        migrations.AlterField(
            model_name='content',
            name='persian_title',
            field=models.CharField(max_length=400, verbose_name='عنوان(فارسی)'),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(max_length=400, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='content',
            name='video',
            field=models.FileField(blank=True, upload_to='videos/content_videos', verbose_name='ویدیو'),
        ),
    ]
