# Generated by Django 4.2.4 on 2023-09-20 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactInformation',
        ),
    ]
