# Generated by Django 4.2.4 on 2023-08-11 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0002_project_cover_image_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'عکس پروژه', 'verbose_name_plural': 'عکس های پروژه ها'},
        ),
        migrations.RemoveField(
            model_name='image',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='images',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects_app.image', verbose_name='عکس های پروژه'),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ManyToManyField(related_name='categories', to='projects_app.category', verbose_name='دسته بندی'),
        ),
    ]
