# Generated by Django 4.2.4 on 2023-08-09 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0002_alter_category_options_alter_project_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
