# Generated by Django 4.2.4 on 2023-08-11 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0003_alter_image_options_remove_image_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(default='title', max_length=100),
        ),
    ]
