# Generated by Django 4.2.4 on 2023-08-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0004_image_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='structure',
            field=models.CharField(choices=[('s', 'structure'), ('i', 'interior'), ('e', 'exterior'), ('o', 'objects')], default='s', max_length=1, verbose_name='نوع پروژه'),
        ),
    ]
