# Generated by Django 4.2.4 on 2023-09-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0005_project_structure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='structure',
        ),
        migrations.AddField(
            model_name='project',
            name='base_category',
            field=models.CharField(choices=[('s', 'structure'), ('i', 'interior'), ('e', 'exterior'), ('o', 'object')], default='s', max_length=1, verbose_name='نوع پروژه'),
        ),
    ]
