# Generated by Django 4.2.4 on 2023-09-09 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0008_alter_project_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True, unique=True),
        ),
    ]
