# Generated by Django 4.2.4 on 2023-09-09 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0011_alter_project_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='images',
        ),
        migrations.AddField(
            model_name='project',
            name='images',
            field=models.ManyToManyField(default=None, to='projects_app.image', verbose_name='عکس های پروژه'),
        ),
    ]
