# Generated by Django 4.2.4 on 2023-09-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0013_alter_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='project_type',
            field=models.CharField(default='projectType', max_length=100, verbose_name='تایپ پروژه(برای توسعه دهندگان)'),
        ),
    ]
