# Generated by Django 4.2.4 on 2023-09-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('about_app', '0002_delete_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/team_members_images', verbose_name='عکس')),
                ('full_name', models.CharField(max_length=300, verbose_name='نام و نام خانوادگی')),
                ('job', models.CharField(max_length=120, verbose_name='شغل')),
                ('persian_job', models.CharField(max_length=120, verbose_name='شغل(فارسی)')),
                ('persian_full_name', models.CharField(max_length=300, verbose_name='نام و نام خانوادگی(فارسی)')),
                ('bio', models.CharField(max_length=500, verbose_name='بایو')),
                ('persian_bio', models.CharField(max_length=500, verbose_name='بایو(فارسی)')),
                ('pdf_file', models.FileField(upload_to='pdfs/article_pdf', verbose_name='فایل')),
            ],
            options={
                'verbose_name': 'عضو تیم',
                'verbose_name_plural': 'افراد تیم',
            },
        ),
    ]
